import math 
import time

def timing():
    start_time = time.time()
    return lambda x: print("[{:.9f}s] {}".format(time.time() - start_time, x))

timer = timing()

lower_limit = 2
upper_limit = 100 + 1

output = []
for a in range(lower_limit, upper_limit, 1):
    for b in range(lower_limit, upper_limit):
        power = math.pow(a, b)
        if power not in output:
            output.append(power)

timer("There are {} distincet terms in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100".format(len(output)))

